version: "2.3"
services:
  web:
    image: hota-product
    container_name: hota_api
    ports:
      - 8888:8888
    depends_on:
      - mysql
    volumes:
      - ./config.json:/app/config.json
  mysql:
    image: mysql:5.7 
    container_name: hota_mysql
    command: mysqld --user=root
    volumes:
      - ./article.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=hota
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root

