app:
  name: "varp_be"
  version: "1.0.0"

http:
  port: "8080"

logger:
  log_level: "debug"
  rollbar_env: "varp_be"

postgres:
  pool_max: 2
  pg_url: "postgres://user:pass@localhost:5432/postgres"

rabbitmq:
  rpc_server_exchange: "rpc_server"
  rpc_client_exchange: "rpc_client"
  rmq_url: "amqp://guest:guest@localhost:5672/"
